
--BORRAR TABLAS

drop table CIUDADANO CASCADE CONSTRAINTS;
drop table USUARIO CASCADE CONSTRAINTS;
drop table PLAN_DE_VACUNACION CASCADE CONSTRAINTS;
drop table MINISTERIO_DE_SALUD CASCADE CONSTRAINTS;
drop table PUNTO_VACUNACION CASCADE CONSTRAINTS;
drop table CITA CASCADE CONSTRAINTS;
drop table TRABAJADOR CASCADE CONSTRAINTS;
drop table VACUNA CASCADE CONSTRAINTS;
drop table OFICINA_REGIONAL_EPS CASCADE CONSTRAINTS;
drop table LIST_CONDICIONES_CIUDADANO CASCADE CONSTRAINTS;
drop table LIST_CONTRAINDICACIONES_VACUNA CASCADE CONSTRAINTS;
drop table CONDICION CASCADE CONSTRAINTS;
drop table TIPO_PUNTO_VACUNACION CASCADE CONSTRAINTS;
drop table ESTADO_VACUNACION CASCADE CONSTRAINTS;
drop table TRABAJO CASCADE CONSTRAINTS;
drop table PRIORIZACION CASCADE CONSTRAINTS;

--DELETE FROM LIST_CONDICIONES_CIUDADANO;
--DELETE FROM LIST_CONTRAINDICACIONES_VACUNA;
--DELETE FROM CITA;
--DELETE FROM VACUNA;
--DELETE FROM PUNTO_VACUNACION;
--DELETE FROM OFICINA_REGIONAL_EPS;
--DELETE FROM TRABAJADOR;
--DELETE FROM USUARIO;
--DELETE FROM CIUDADANO;
--DELETE FROM MINISTERIO_DE_SALUD;
--DELETE FROM PLAN_DE_VACUNACION;
--DELETE FROM CONDICION;
--DELETE FROM TIPO_PUNTO_VACUNACION ;
--DELETE FROM ESTADO_VACUNACION;
--DELETE FROM TRABAJO;
--DELETE FROM PRIORIZACION;



--DELETE FROM LIST_CONDICIONES_CIUDADANO;
--DELETE FROM LIST_CONTRAINDICACIONES_VACUNA;
--DELETE FROM CITA;
--DELETE FROM VACUNA;
--DELETE FROM PUNTO_VACUNACION;
--DELETE FROM OFICINA_REGIONAL_EPS;
--DELETE FROM USUARIO;
--DELETE FROM TRABAJADOR;
--DELETE FROM CIUDADANO;
--DELETE FROM MINISTERIO_DE_SALUD;
--DELETE FROM PLAN_DE_VACUNACION;

--DELETE FROM CIUDADANO;