
ALTER SESSION SET CURRENT_SCHEMA = ISIS2304D10202110; -- triana
--ALTER SESSION SET CURRENT_SCHEMA = ISIS2304D06202110; --ramirez

--PLAN_DE_VACUNACION
INSERT INTO PLAN_DE_VACUNACION ( NOMBRE, DESCRIPCION, FECHA_ACTUALIZACION) VALUES ( 'Plan 1 Colombia', 'Descripcion de prueba', TO_DATE('2021/04/07 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));

--MINISTERIO_SALUD
INSERT INTO MINISTERIO_DE_SALUD (PLAN_DE_VACUNACION) VALUES (1);

--CIUDADANO
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168160,'Santiago Triana', NULL, 'Andina', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168161,'Juan Sebastian Ramirez', NULL, 'Andina', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168162,'Alexander Amores', NULL, 'Andina', 0, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168163,'Maria Sandoval', NULL, 'Andina', 0, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168164,'Geronimo Gonzales', NULL, 'Andina', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168165,'Benedicta Ramirez', NULL, 'Andina', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168166,'Adolfo Perez', NULL, 'Andina', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168167,'Roberto Giraldo', NULL, 'Caribe', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168168,'Nestor Guevara', NULL, 'Caribe', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168169,'Marta Contreras', NULL, 'Caribe', 1, NULL, NULL, NULL);
INSERT INTO CIUDADANO (CEDULA, NOMBRE_COMPLETO, ESTADO_VACUNACION, REGION, DESEA_SER_VACUNADO,PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL_ASIGNADA) VALUES (1001168170,'Elisa Madrid', NULL, 'Caribe', 1, NULL, NULL, NULL);

--USUARIO
INSERT INTO USUARIO (USERNAME,CONTRASENA,CORREO,PLAN_DE_VACUNACION,CIUDADANO) VALUES ('a.trianaa','contrasena1','a.trianaa@uniandes.edu.co', 1, '1001168160');
INSERT INTO USUARIO (USERNAME,CONTRASENA,CORREO,PLAN_DE_VACUNACION,CIUDADANO) VALUES ('j.ramirezb','contrasena2','j.ramirez@uniandes.edu.co', 1, '1001168161');
INSERT INTO USUARIO (USERNAME,CONTRASENA,CORREO,PLAN_DE_VACUNACION,CIUDADANO) VALUES ('alemores','contrasena3','alemores@gmail.com', 1, '1001168162');
INSERT INTO USUARIO (USERNAME,CONTRASENA,CORREO,PLAN_DE_VACUNACION,CIUDADANO) VALUES ('maria123','contrasena4','maria123@yahoo.es', 1, '1001168163');


--TRABAJADOR
INSERT INTO TRABAJADOR (CEDULA, TRABAJO, ADMINISTRADOR_VACUANDES) VALUES (1001168160, 'Administrador plan de vacunacion', 1);
INSERT INTO TRABAJADOR (CEDULA, TRABAJO, ADMINISTRADOR_VACUANDES) VALUES (1001168161, 'Administrador punto vacunacion', 1);
INSERT INTO TRABAJADOR (CEDULA, TRABAJO, ADMINISTRADOR_VACUANDES) VALUES (1001168162, 'Administrador oficina punto regional eps', 1);
INSERT INTO TRABAJADOR (CEDULA, TRABAJO, ADMINISTRADOR_VACUANDES) VALUES (1001168163, 'Operador punto vacunacion', 1);

--OFICINA_REGIONAL_EPS
INSERT INTO OFICINA_REGIONAL_EPS (REGION, ADMINISTRADOR, CANTIDAD_VACUNAS_ENVIABLES, CANTIDAD_VACUNAS_ACTUALES, PLAN_DE_VACUNACION) VALUES ('Andina', 'alemores', 200000, 0, 1);
INSERT INTO OFICINA_REGIONAL_EPS (REGION, ADMINISTRADOR, CANTIDAD_VACUNAS_ENVIABLES, CANTIDAD_VACUNAS_ACTUALES, PLAN_DE_VACUNACION) VALUES ('Caribe', 'alemores', 200000, 0, 1);

--PUNTO_DE_VACUNACION
INSERT INTO PUNTO_VACUNACION (LOCALIZACION, CAPACIDAD_DE_ATENCION_SIMULTANEA, INFRAESTRUCTURA_PARA_DOSIS, CANTIDAD_VACUNAS_ENVIABLES, CANTIDAD_VACUNAS_ACTUALES, TIPO_PUNTO_VACUNACION, ADMINISTRADOR, OFICINA_REGIONAL_EPS, HABILITADO)
VALUES ('Cra 54#178-12 Oficina 1', 2, 'Congeladores, Cubiculos separados', 500, 3, 'Centro de salud', 'j.ramirezb',1,1);
INSERT INTO PUNTO_VACUNACION (LOCALIZACION, CAPACIDAD_DE_ATENCION_SIMULTANEA, INFRAESTRUCTURA_PARA_DOSIS, CANTIDAD_VACUNAS_ENVIABLES, CANTIDAD_VACUNAS_ACTUALES, TIPO_PUNTO_VACUNACION, ADMINISTRADOR, OFICINA_REGIONAL_EPS, HABILITADO)
VALUES ('Calle 12#57-34', 1, 'Todos los necesarios', 3000, 5, 'Hospital', 'j.ramirezb',1,1);
INSERT INTO PUNTO_VACUNACION (LOCALIZACION, CAPACIDAD_DE_ATENCION_SIMULTANEA, INFRAESTRUCTURA_PARA_DOSIS, CANTIDAD_VACUNAS_ENVIABLES, CANTIDAD_VACUNAS_ACTUALES, TIPO_PUNTO_VACUNACION, ADMINISTRADOR, OFICINA_REGIONAL_EPS, HABILITADO)
VALUES ('Diagonal 123 #14', 30, 'Cubiculos separados', 1000, 0, 'Otro', 'j.ramirezb',2,1);


--VACUNA
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 1);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 1);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 1);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 1);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 1);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 1);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 1);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 1, 1, 1, 0);

INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 2, 1, 1, 1);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 2, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 2, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 2, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 2, 1, 1, 0);
INSERT INTO VACUNA (CONDICION_PRESERVACION, PUNTO_VACUNACION, PLAN_DE_VACUNACION, OFICINA_REGIONAL, UTILIZADA)
VALUES ('Congelada', 2, 1, 1, 0);

--CITA
INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA, HORA_CITA) VALUES (TO_DATE('2020/06/08', 'yyyy/mm/dd'),1001168160,1,1,1200);
INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA, HORA_CITA) VALUES (TO_DATE('2021/06/07', 'yyyy/mm/dd'),1001168161,1,2,1200);
INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA, HORA_CITA) VALUES (TO_DATE('2021/07/07', 'yyyy/mm/dd'),1001168160,1,3,1600);
INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA, HORA_CITA) VALUES (TO_DATE('2021/07/07', 'yyyy/mm/dd'),1001168162,1,4,1600);
INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA, HORA_CITA) VALUES (TO_DATE('2021/07/07', 'yyyy/mm/dd'),1001168162,1,5,1600);
INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA, HORA_CITA) VALUES (TO_DATE('2021/08/08', 'yyyy/mm/dd'),1001168162,1,6,1200);
INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA, HORA_CITA) VALUES (TO_DATE('2021/08/08', 'yyyy/mm/dd'),1001168162,1,7,1200);

INSERT INTO CITA (FECHA, CIUDADANO, PUNTO_VACUNACION, VACUNA, HORA_CITA) VALUES (TO_DATE('2021/07/07', 'yyyy/mm/dd'),1001168162,2,11,1200);

--Update de los ciudadano con puntos de vacunaci�n y regiones
UPDATE ciudadano SET PUNTO_VACUNACION= 1, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 1 WHERE CEDULA = 1001168160;
UPDATE ciudadano SET PUNTO_VACUNACION= 1, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 1 WHERE CEDULA = 1001168161;
UPDATE ciudadano SET PUNTO_VACUNACION= 1, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 1 WHERE CEDULA = 1001168162;
UPDATE ciudadano SET PUNTO_VACUNACION= 2, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 1 WHERE CEDULA = 1001168163;
UPDATE ciudadano SET PUNTO_VACUNACION= 2, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 1 WHERE CEDULA = 1001168164;
UPDATE ciudadano SET PUNTO_VACUNACION= 2, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 1 WHERE CEDULA = 1001168165;
UPDATE ciudadano SET PUNTO_VACUNACION= 2, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 1 WHERE CEDULA = 1001168166;
UPDATE ciudadano SET PUNTO_VACUNACION= 3, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 2 WHERE CEDULA = 1001168167;
UPDATE ciudadano SET PUNTO_VACUNACION= 3, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 2 WHERE CEDULA = 1001168168;
UPDATE ciudadano SET PUNTO_VACUNACION= 3, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 2 WHERE CEDULA = 1001168169;
UPDATE ciudadano SET PUNTO_VACUNACION= 3, PLAN_DE_VACUNACION= 1, OFICINA_REGIONAL_ASIGNADA = 2 WHERE CEDULA = 1001168170;

commit;