ALTER SESSION SET CURRENT_SCHEMA = ISIS2304D06202110; --ramirez
SELECT id_Punto_Vacunacion,LOCALIZACION,CAPACIDAD_DE_ATENCION_SIMULTANEA,INFRAESTRUCTURA_PARA_DOSIS,CANTIDAD_VACUNAS_ENVIABLES,CANTIDAD_VACUNAS_ACTUALES,TIPO_PUNTO_VACUNACION,ADMINISTRADOR,OFICINA_REGIONAL_EPS, HABILITADO FROM PUNTO_VACUNACION WHERE HABILITADO = 1;

UPDATE punto_vacunacion SET habilitado = 0 WHERE ID_PUNTO_VACUNACION = 1;

SELECT TO_CHAR(SYSDATE, 'DD-MON-YYYY HH:MI:SS') FROM dual;

SELECT * FROM cita WHERE PUNTO_VACUNACION = 1 AND FECHA >= (SELECT TO_CHAR(SYSDATE, 'DD-MON-YYYY') FROM dual);

SELECT punto_vacunacion, COUNT(id_cita) FROM cita GROUP BY punto_vacunacion;

INSERT INTO estado_vacunacion (ESTADO) values 'Vacunado completamente'